//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onMuhasebeApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class carkEntities : DbContext
    {
        public carkEntities()
            : base("name=carkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBL_Companies> TBL_Companies { get; set; }
        public virtual DbSet<TBL_Personel> TBL_Personel { get; set; }
        public virtual DbSet<TBL_Money> TBL_Money { get; set; }
        public virtual DbSet<TBL_Customers> TBL_Customers { get; set; }
        public virtual DbSet<TBL_Suppliers> TBL_Suppliers { get; set; }
        public virtual DbSet<TBL_Stock> TBL_Stock { get; set; }
    }
}
