//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onMuhasebeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Money
    {
        public int money_ID { get; set; }
        public Nullable<int> company_ID { get; set; }
        public string money_TITLE { get; set; }
        public string money_DESCRIPTION { get; set; }
        public string money_TYPE { get; set; }
        public string money_COMPANY { get; set; }
        public string money_CURRENCY { get; set; }
        public Nullable<System.DateTime> money_DATE { get; set; }
        public Nullable<decimal> money_AMOUNT { get; set; }
    
        public virtual TBL_Companies TBL_Companies { get; set; }
    }
}
