//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onMuhasebeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Customers
    {
        public int customer_ID { get; set; }
        public Nullable<int> company_ID { get; set; }
        public string customer_NAME { get; set; }
        public string customer_DESCRIPTION { get; set; }
        public string customer_ADDRESS { get; set; }
        public string customer_TELNO { get; set; }
    
        public virtual TBL_Companies TBL_Companies { get; set; }
    }
}
