//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onMuhasebeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Stock
    {
        public int stock_ID { get; set; }
        public Nullable<int> company_ID { get; set; }
        public string stock_NAME { get; set; }
        public string stock_TYPE { get; set; }
        public Nullable<decimal> stock_PRICE { get; set; }
        public Nullable<int> stock_PIECE { get; set; }
        public Nullable<System.DateTime> stock_ADDTIME { get; set; }
        public string stock_MODEL { get; set; }
    
        public virtual TBL_Companies TBL_Companies { get; set; }
    }
}
