//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onMuhasebeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Companies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Companies()
        {
            this.TBL_Personel = new HashSet<TBL_Personel>();
            this.TBL_Money = new HashSet<TBL_Money>();
            this.TBL_Customers = new HashSet<TBL_Customers>();
            this.TBL_Suppliers = new HashSet<TBL_Suppliers>();
            this.TBL_Stock = new HashSet<TBL_Stock>();
        }
    
        public int company_ID { get; set; }
        public string company_NAME { get; set; }
        public string company_sector { get; set; }
        public string company_USERN { get; set; }
        public string company_PASSWORD { get; set; }
        public string company_ActivasionKey { get; set; }
        public string company_Role { get; set; }
        public string company_LOGO { get; set; }
        public string company_ADDRESS { get; set; }
        public string company_COUNTRY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Personel> TBL_Personel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Money> TBL_Money { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Customers> TBL_Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Suppliers> TBL_Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Stock> TBL_Stock { get; set; }
    }
}
